name:                dep-tt
version:             0.1.0.0
github:              "githubuser/dep-tt"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/dep-tt#readme>

dependencies:
- base >= 4.7 && < 5
- unbound-generics
- mtl
- pretty
- megaparsec
- parser-combinators
- transformers
- containers

library:
  source-dirs: src

default-extensions:
  DeriveGeneric
  MultiParamTypeClasses
  DeriveAnyClass
  DerivingStrategies
  FlexibleInstances

executables:
  dep-tt-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dep-tt

tests:
  dep-tt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dep-tt
    - HUnit
